// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellClues } from "./CellClues";
import type { Style } from "./Style";

export type Cell = { "type": "block", styles: Array<Style>, } | { "type": "letter", solution: string, number: number | null, clues: CellClues, styles: Array<Style>, prefilled: string | null, };
