// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Direction } from "./Direction";

export type Clue = { id: string, number: number, direction: Direction, body: string, answer: string, indexes: Array<number>, splits: Array<number>, hint: string | null, refs: Array<string>, metadata: { [key in string]: string }, };
