// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Meta = { title: string | null, author: string | null, date: string | null, copyright: string | null, description: string | null, notes: string | null, id: string | null, difficulty: number | null, extra: { [key in string]: string }, };
