// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from "./Cell";
import type { Clue } from "./Clue";
import type { Meta } from "./Meta";

export type Puzzle = { meta: Meta, width: number, height: number, cells: Array<Cell>, rebuses: { [key in string]: string }, clues: { [key in string]: Clue }, clueOrder: Array<string>, };
