// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UiAction = "start" | "dismiss" | "reset" | "hint" | "prev-clue" | "next-clue" | "toggle-direction" | "toggle-rebus" | "check-cell" | "check-word" | "check-puzzle" | "reveal-cell" | "reveal-word" | "reveal-puzzle";
