[package]
name = "crossword-dot-blue"
version.workspace = true
edition.workspace = true
build = "build.rs"

[features]
local = ["boutique/devtools"]

[dependencies]
axum = { version = "0.8.9", features = ["multipart"] }
axum-extra = { version = "0.10", features = ["cookie"] }
boutique = { git = "https://github.com/avavuvu/boutique.git", rev = "009486ce077a5e21e5bee8b3aae8d8216742c388", features = ["migration", "cloudinary"] }
bq_components = { git = "https://github.com/avavuvu/boutique.git", rev = "009486ce077a5e21e5bee8b3aae8d8216742c388" }
chrono = "0.4.45"
crossword-tools = { path = "../crossword-tools" }
dotenvy = "0.15.7"
markdown = "1"
migration = { path = "../migration" }
maud = { version = "0.27.0", features = ["axum"] }
nanorand = "0.8.0"
sea-orm = { version = "1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
serde = "1.0.229"
serde_json = "1"
slugify = "0.1.0"
time = "0.3"
tokio = { version = "1", features = ["full"] }
ts-rs = { version = "12", features = ["serde-compat"] }
validator = { version = "0.20", features = ["derive"] }

[build-dependencies]
markdown = "1"
